export default {
  INTERNAL_ERROR: "INTERNAL_ERROR",
  BAD_REQUEST: "BAD_REQUEST",
  UPDATE_FAILED: "UPDATE_FAILED",
  CREATION_FAILED: "CREATION_FAILED",
  DELETE_FAILTED: "DELETE_FAILED",
  ALREADY_EXIST: "ALREADY EXIST",
};
