export const UserListConstants = {
  GET_USER_LIST: "GET_USER_LIST",
  GET_USER_LIST_SUCCESS: "GET_USER_LIST_SUCCESS",
  GET_USER_LIST_ERROR_SHOW: "GET_USER_LIST_ERROR_SHOW",
  GET_USER_LIST_ERROR_HIDE: "GET_USER_LIST_ERROR_HIDE",
  GET_USER_LIST_CLEAR: "GET_USER_LIST_CLEAR",
};

export const UserCreateConstants = {
  USER_CREATE: "USER_CREATE",
  USER_CREATE_SUCCESS: "USER_CREATE_SUCCESS",
  USER_CREATE_ERROR_SHOW: "USER_CREATE_ERROR_SHOW",
  USER_CREATE_ERROR_HIDE: "USER_CREATE_ERROR_HIDE",
};

export const UserDeleteConstants = {
  USER_DELETE: "USER_DELETE",
  USER_DELETE_SUCCESS: "USER_DELETE_SUCCESS",
  USER_DELETE_ERROR_SHOW: "USER_DELETE_ERROR_SHOW",
  USER_DELETE_ERROR_HIDE: "USER_DELETE_ERROR_HIDE",
};

export const UserDetailConstants = {
  USER_DETAIL: "USER_DETAIL",
  USER_DETAIL_SUCCESS: "USER_DETAIL_SUCCESS",
  USER_DETAIL_ERROR_SHOW: "USER_DETAIL_ERROR_SHOW",
  USER_DETAIL_ERROR_HIDE: "USER_DETAIL_ERROR_HIDE",
  USER_DETAIL_CLEAR: "USER_DETAIL_CLEAR",
};

export const UserUpdateConstants = {
  USER_UPDATE: "USER_UPDATE",
  USER_UPDATE_SUCCESS: "USER_UPDATE_SUCCESS",
  USER_UPDATE_ERROR_SHOW: "USER_UPDATE_ERROR_SHOW",
  USER_UPDATE_ERROR_HIDE: "USER_UPDATE_ERROR_HIDE",
};
